name: 'Test'
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality:
    name: "Code Quality"
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: "Set up nightly Rust" # https://github.com/rust-lang/rustup/issues/3409
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-11-29 # Hardcoded version, same as is in the build.rs

      - name: 'Build smir_pretty' # rustfmt documentation claims it is unstable on code that doesn't build
        run: |
          cargo build -vv

      - name: "Check `cargo clippy`"
        run: |
          rustup component add clippy
          cargo clippy -- -Dwarnings

      - name: "Check `cargo fmt`"
        run: |
          rustup component add rustfmt
          cargo fmt --check

  integration-tests:
    name: "Integration tests"
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: "Set up nightly Rust" # https://github.com/rust-lang/rustup/issues/3409
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-11-29 # Hardcoded version, same as is in the build.rs

      - name: 'Build smir_pretty'
        run: | # Warning check should be redundant
          RUSTFLAGS='--deny warnings' cargo build -vv

      - name: 'Run smir integration tests'
        run: |
          make integration-test