name: 'Test'
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Greet
      run: echo "Hello from CI"
